name: "Rectorize"

on: workflow_dispatch

jobs:
  rector:
    name: "Rector"
    runs-on: ubuntu-latest
    steps:
      - name: Set PHP version
        run: sudo update-alternatives --set php /usr/bin/php8.0

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Composer
        uses: actions/cache@v1
        with:
          path: ${{ steps.vars.outputs.composer-cache-path }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --no-interaction

      - name: Rectify project
        run: vendor/bin/rector process easy-watermark.php src

      - name: Fix code style
        continue-on-error: true
        run: composer phpcbf

      - name: Check Code Compatibility
        run: composer phpcompat

      - name: Lint Code
        run: composer phplint

      - name: Remove dev dependencies
        run: composer install --no-dev --no-progress --no-interaction

      - name: Build tar archive
        run: tar -cf build.tar .

      - name: Upload rectified source code
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: build.tar
          retention-days: 1
